version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      - checkout
      - run:
          name: Mirror push to submission repo
          command: bash .circleci/mirror.sh
